[general]
import = [
#    "C:\\Users\\Inplikt\\AppData\\Roaming\\alacritty\\themes\\themes\\taerminal.toml"
]

# Default colors
[colors.primary]
background = '#1c1c1c'
foreground = '#f0f0f0'

[colors.cursor]
background = '#f0f0f0'
foreground = '#26282a'

# Normal colors
[colors.normal]
black   = '#333f4a'
red     = '#ff4562'
green   = '#b4fb73'
yellow  = '#fff854'
blue    = '#78bcf5'
magenta = '#ffb2fe'
cyan    = '#00ffff'
white   = '#f1f1f1'

# Bright colors
[colors.bright]
black   = '#6f6f6f'
red     = '#ff8598'
green   = '#d6fcba'
yellow  = '#fffa80'
blue    = '#c2e3ff'
magenta = '#ffc6ff'
cyan    = '#a1ffff'
white   = '#ffffff'


[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
LANG = "en_US.UTF-8"

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BR"
key = "R"
mods = "Command"

[window]
decorations = "None"
dynamic_padding = true
opacity = 0.95
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[cursor]
style = { shape = "Beam", blinking = "Always" }

[terminal.shell]
program = "wsl"
args = [
    "-d",
    "Ubuntu-22.04",
    "--cd",
    "~"
]
